---
- name: "Create the default ACME account"
  proxmox_acme_account:
    contact: "{{ pve_acme_contact }}"
    directory: "{{ pve_acme_directory | default(omit) }}"
  when: "not pve_cluster_enabled | bool or (pve_cluster_enabled | bool and inventory_hostname == groups[pve_group][0])"

- name: "Read ACME Domains"
  command: "pvenode config get -property acme"
  changed_when: false
  register: "_acme_domain"

- block:
    - name: "Define ACME Domains"
      command: pvenode config set --acme domains={{ ansible_fqdn }}

    - name: "Register ACME Domains"
      command: pvenode acme cert order
  when: "ansible_fqdn not in _acme_domain.stdout"
