---
- name: "Create all aliases"
  proxmox_firewall_alias:
    name: "{{ pve_firewall_alias.name }}"
    cidr: "{{ pve_firewall_alias.cidr }}"
    comment: "{{ pve_firewall_alias.comment }}"
  loop: "{{ pve_firewall_aliases | default([]) }}"
  loop_control:
    loop_var: pve_firewall_alias

- name: "Create all IPset configurations"
  proxmox_firewall_ipset:
    name: "{{ pve_firewall_ipset.key }}"
    entries: "{{ pve_firewall_ipset.value }}"
  loop: "{{ pve_firewall_ipsets | default({}) | dict2items }}"
  loop_control:
    loop_var: pve_firewall_ipset

- name: "Manage Cluster configuration"
  include_tasks: firewall_group.yml
  with_items: "{{ pve_firewall_groups | default([]) }}"
  loop_control:
    loop_var: pve_firewall_group

- name: "Read current Cluster Firewall Status"
  command: "pvesh get cluster/firewall/options --output-format json"
  changed_when: false
  register: _pve_firewall_cluster_status

- name: "Enable Cluster Firewall"
  command: "pvesh set cluster/firewall/options enable=1"
  when:
    - "pve_firewall_cluster_enabled | bool"
    - "1 == (_pve_firewall_cluster_status.stdout | from_json | json_query('enable'))"
