# TODO replace specific inventory structure to a dict
# per host:
#   network.wan.ipv4.address
#   network.wan.ipv6.address
#   network.lan.ipv4.address
#   network.lan.ipv6.address
#   network.vpn.ipv4.address
#   network.vpn.ipv6.address
#
# any ideas for a good dict?
#
# pve_firewall_aliases:
#   - name: xyz
#     cidr: 1.2.3.4
---
- name: "Create all IPv4 aliases"
  proxmox_firewall_alias:
    name: "{{ hostvars[host].infrastructure.hostname }}-wan-ipv4"
    cidr: "{{ hostvars[host].network.ipv4.address }}"
    comment: "{{ hostvars[host].infrastructure.fqdn }}"
  when:
    - "hostvars[host].network is defined"
    - "hostvars[host].network.ipv4 is defined"
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: host

- name: "Create all IPv6 aliases"
  proxmox_firewall_alias:
    name: "{{ hostvars[host].infrastructure.hostname }}-wan-ipv6"
    cidr: "{{ hostvars[host].network.ipv6.address }}"
    comment: "{{ hostvars[host].infrastructure.fqdn }}"
  when:
    - "hostvars[host].network is defined"
    - "hostvars[host].network.ipv6 is defined"
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: host


- name: "Create all VPN IPv4 aliases"
  proxmox_firewall_alias:
    name: "{{ hostvars[host].infrastructure.hostname }}-vpn-ipv4"
    cidr: "{{ hostvars[host].network.vpn.ipv4_address }}"
    comment: "{{ hostvars[host].infrastructure.fqdn }}"
  when:
    - "hostvars[host].network is defined"
    - "hostvars[host].network.vpn is defined"
    - "hostvars[host].network.vpn.ipv4_address is defined"
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: host

- name: "Create all VPN IPv6 aliases"
  proxmox_firewall_alias:
    name: "{{ hostvars[host].infrastructure.hostname }}-vpn-ipv6"
    cidr: "{{ hostvars[host].network.vpn.ipv6_address }}"
    comment: "{{ hostvars[host].infrastructure.fqdn }}"
  when:
    - "hostvars[host].network is defined"
    - "hostvars[host].network.vpn is defined"
    - "hostvars[host].network.vpn.ipv6_address is defined"
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: host


- name: "Create all LAN IPv4 aliases"
  proxmox_firewall_alias:
    name: "{{ hostvars[host].infrastructure.hostname }}-lan-ipv4"
    cidr: "{{ hostvars[host].network.lan.ipv4.address }}"
    comment: "{{ hostvars[host].infrastructure.fqdn }}"
  when:
    - "hostvars[host].network is defined"
    - "hostvars[host].network.lan is defined"
    - "hostvars[host].network.lan.ipv4 is defined"
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: host

- name: "Create all LAN IPv6 aliases"
  proxmox_firewall_alias:
    name: "{{ hostvars[host].infrastructure.hostname }}-lan-ipv6"
    cidr: "{{ hostvars[host].network.lan.ipv6.address }}"
    comment: "{{ hostvars[host].infrastructure.fqdn }}"
  when:
    - "hostvars[host].network is defined"
    - "hostvars[host].network.lan is defined"
    - "hostvars[host].network.lan.ipv6 is defined"
  with_items: "{{ groups['all'] }}"
  loop_control:
    loop_var: host
